[package]
name = "kanter_core"
version = "0.1.0"
authors = ["Lukas Orsvärn <lukas@orsvarn.com>"]
edition = "2018"

[dependencies]
image = "0.20.1"
rand = "0.5.0"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
nalgebra = "~0.10"