[package]
name = "kanter_core"
version = "0.4.0"
authors = ["Lukas Orsvärn <lukas@orsvarn.com>"]
edition = "2018"

[dependencies]
image = "0.20.1"
nalgebra = "~0.10"
rand = "0.5.0"
tempfile = "3.2"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"

[dev-dependencies]
ntest = "0.7.3"
